apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Environment approvals
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Fake build
        uses: docker://alpine:3.18
        run: echo Building
  deploy:
    environment: test
    steps:
      - name: Fake deploy
        uses: docker://alpine:3.18
        run: echo Deploying to test
    needs: build