apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Environment approval
on:
  push:
    branches:
      - "**"
jobs:
  deploy:
    environment: test
    steps:
      - name: Fake deploy
        uses: docker://alpine:3.18
        run: echo Deploying to test
